"""episode video_path nullable

Revision ID: e86e2b58afbf
Revises: af9d7ef5355c
Create Date: 2026-09-03 01:49:43.554272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86e2b58afbf'
down_revision: Union[str, None] = 'af9d7ef5355c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.alter_column('video_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.alter_column('video_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    # ### end Alembic commands ###
